### ISSUE TITLE
terraform plan fails with " no valid credential sources for Terraform AWS Provider found."

### ISSUE THREAD

**Issue by henryjarend** [ManagedKube/kubernetes-ops#381]
Version:
Terraform cli: 1.3.2
kubernetes-ops release: v2.0.47
module: eks
Issue:
When trying to run a plan, it errors out with ` error configuring Terraform AWS Provider: no valid credential sources for Terraform AWS Provider found.` I've updated my VPC to match release versions and running plans for other modules in the same tenant are working. (credentials are shared across so shouldn't be a credentials issue). I do see that there's a call to the metadata API IP that's getting a connection refused. I don't think I have anything 'incorrect' however I can't see to get it to work either
Full Error message:
```
Terraform v1.3.2
on linux_amd64
Initializing plugins and modules...
data.terraform_remote_state.vpc: Reading...
data.terraform_remote_state.vpc: Read complete after 1s
╷
│ Warning: Redundant ignore_changes element
│
│   on .terraform/modules/eks.eks/main.tf line 305, in resource "aws_eks_addon" "this":
│  305: resource "aws_eks_addon" "this" {
│
│ Adding an attribute name to ignore_changes tells Terraform to ignore future
│ changes to the argument in configuration after the object has been created,
│ retaining the value originally configured.
│
│ The attribute modified_at is decided by the provider alone and therefore
│ there can be no configured value to compare with. Including this attribute
│ in ignore_changes has no effect. Remove the attribute from ignore_changes
│ to quiet this warning.
╵
╷
│ Error: error configuring Terraform AWS Provider: no valid credential sources for Terraform AWS Provider found.
│
│ Please see https://registry.terraform.io/providers/hashicorp/aws
│ for more information about providing credentials.
│
│ Error: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, request send failed, Get "http://169.254.169.254/latest/meta-data/iam/security-credentials/": dial tcp 169.254.169.254:80: i/o timeout
│
│
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on main.tf line 35, in provider "aws":
│   35: provider "aws" {
│
╵
Operation failed: failed running terraform plan (exit 1)
```

**Comment by sekka1** [comment]
@henryjarend did this work for you before and it just stopped working or are you just trying to get this working for the first time?

**Comment by henryjarend** [comment]
I've never gotten it to work. I've tried a couple different times using as close to default values as possible and it failed both times

**Comment by sekka1** [comment]
Are you running this locally or through the Github Action pipeline?

**Comment by henryjarend** [comment]
Runs are from terraform cloud. My best guess is that there's some IMDS role that's missing from EC2 but I'm not sure where that should come from or be created at. I know that I have my AWS API tokens inserted correctly because I was able to downgrade the module version back to a v1 and it worked without any issues. If you need any more info let me know

**Comment by sekka1** [comment]
From your above post...you have:

```
data.terraform_remote_state.vpc: Reading...
data.terraform_remote_state.vpc: Read complete after 1s
```

Were you able to instantiate the VPC successfully through the same Terraform Cloud account?

**Comment by henryjarend** [comment]
yep! Everything up to that point worked without a hitch (route53, VPC) and then it gets caught up on the EKS deploy section. I was able to get a little more information out of logs
It seems like one of the modules being used by the managed-kube module (module.eks.module.eks.kubernetes_config_map.aws_auth[0]) is trying to create some aws_auth object and that's what's been causing the issue. From what I can tell the variable that controls the creation is set to false so I'm not sure why it's still trying to create it.

**Comment by sekka1** [comment]
Ah yes..there were some changes to the source EKS module on how they handled the aws_auth config map.

Which EKS module version are you using?

See: https://github.com/ManagedKube/kubernetes-ops/releases/tag/v2.0.29 (informational on what happened to the aws auth config map)

The latest EKS module version is and you should use: https://github.com/ManagedKube/kubernetes-ops/releases/tag/v2.0.37

More information:
* We wrap around the official AWS EKS Terraform module: https://github.com/ManagedKube/kubernetes-ops/tree/main/terraform-modules/aws/eks
* We do this b/c it is not sufficient to just use that module, you have to add in other items like KMS and Cloudwatch logs settings.  
* So to make it easier we wrap around the offical EKS module and add in the items that we have seen our consulting clients needs.

**Comment by henryjarend** [comment]
I was trying to use 2.0.48 but swapped to 2.0.37 and I'm still getting the same error. If I started on a v1.something and then tried to move up to v2 is there a migration path that either doesn't exist (meaning I just need to start from v2) or is there a certain set of versions I need go to through.
Based on the run logs I'm seeing it seems like Terraform is trying to manage a self managed cluster (as opposed to the EKS managed cluster I'm using)
```
{"@level":"error","@message":"Error: Get \"http://localhost/api/v1/namespaces/kube-system/configmaps/aws-auth\": dial tcp [::1]:80: connect: connection refused","@module":"terraform.ui","@timestamp":"2022-11-01T11:50:38.876011Z","diagnostic":{"severity":"error","summary":"Get \"http://localhost/api/v1/namespaces/kube-system/configmaps/aws-auth\": dial tcp [::1]:80: connect: connection refused","detail":"","address":"module.eks.module.eks.kubernetes_config_map.aws_auth[0]","range":{"filename":".terraform/modules/eks.eks/main.tf","start":{"line":426,"column":45,"byte":14798},"end":{"line":426,"column":46,"byte":14799}},"snippet":{"context":"resource \"kubernetes_config_map\" \"aws_auth\"","code":"resource \"kubernetes_config_map\" \"aws_auth\" {","start_line":426,"highlight_start_offset":44,"highlight_end_offset":45,"values":[]}},"type":"diagnostic"}
```
I'm specifically looking at the section saying that trying to get http://localhost errored out. I'm pretty sure that should be trying to call the EKS endpoint. When I scrubbed through both the managed-kube module and the referenced module it seems like the variable for the self managed aws auth resource is set to false but it's still trying to plan that section

**Comment by sekka1** [comment]
Are you building a new cluster or trying to apply it to the current one that is already there?

**Comment by henryjarend** [comment]
looks like building a whole new cluster worked. It ended up causing some issues because of any deployed helm charts that I had created via terraform but once I re-applied all of those it seems to be back up and running.
Any idea if this will come up again? I know that might be like trying to look into a crystal ball but just want to make sure that if I get into the same situation I have a way out without re-deploying everything

**Comment by sekka1** [comment]
No...we have been using this for a while now and it has not come up.

This was a headache for us as well.

Take a look at this PR that reverts the aws-auth usage back: https://github.com/ManagedKube/kubernetes-ops/pull/322/files#diff-09c5a507d650b51f4ac7b3c9ed6351d1949518d777d18ebff6ea6621c8d5b4aaL68-L79

We wrap around the official AWS EKS terraform module (https://github.com/terraform-aws-modules/terraform-aws-eks/releases/tag/v18.0.0) b/c we have to use this module and add some more stuff to make EKS fully functional.

So a while back they said the AWS EKS terraform module should concern itself with the aws-auth b/c it was outside of the scope.  However, it really wasnt.  In the PR i link to an issue where a lot of people were complaining.

Subsequently the AWS EKS terraform module added it back in.

Hence this breaking change.

I dont think you will see this specific issue again and I think the AWS EKS terraform module team is now aware that making these kind of breaking changes is not good for their community base.  I dont expect to see this particular issue.  Hopefully 🤞

**Comment by henryjarend** [comment]
I'll go sacrifice my typical IT goat and hope that it doesn't come up again either! Thanks so much for your help!
