### ISSUE TITLE
Versions not compatible

### ISSUE THREAD

**Issue by jacquesvermak** [ManagedKube/kubernetes-ops#444]
eks autoscaler
 config:
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 3.37.0"
    }
    helm = {
      source  = "hashicorp/helm"
      version = "2.5.0"
    }

module "cluster-autoscaler" {
  source = "github.com/ManagedKube/kubernetes-ops//terraform-modules/aws/cluster-autoscaler?ref=v2.0.82"

error:

 Error: Unsupported attribute
│ 
│   on main.tf line 58, in provider "helm":
│   58:     host                   = data.terraform_remote_state.eks.outputs.cluster_endpoint
│     ├────────────────
│     │ data.terraform_remote_state.eks.outputs is object with no attributes
│ 
│ This object does not have an attribute named "cluster_endpoint".
╵
╷
│ Error: Unsupported attribute
│ 
│   on main.tf line 59, in provider "helm":
│   59:     cluster_ca_certificate = base64decode(data.terraform_remote_state.eks.outputs.cluster_certificate_authority_data)
│     ├────────────────
│     │ data.terraform_remote_state.eks.outputs is object with no attributes
│ 
│ This object does not have an attribute named
│ "cluster_certificate_authority_data".

╷
│ Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"
│
│ with module.cluster-autoscaler.module.cluster-autoscaler.helm_release.helm_chart,
│ on .terraform/modules/cluster-autoscaler.cluster-autoscaler/terraform-modules/aws/helm/helm_generic/[main.tf](http://main.tf/) line 1, in resource "helm_release" "helm_chart":
│ 1: resource "helm_release" "helm_chart" {
│
╵
Operation failed: failed running terraform apply (exit 1)

Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"
│ 
│   with module.cluster-autoscaler.module.cluster-autoscaler.helm_release.helm_chart,
│   on .terraform/modules/cluster-autoscaler.cluster-autoscaler/terraform-modules/aws/helm/helm_generic/main.tf line 1, in resource "helm_release" "helm_chart":
│    1: resource "helm_release" "helm_chart" {
│ 

kube prometheus stack

config:
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 3.37.0"
    }
    random = {
      source = "hashicorp/random"
    }
    helm = {
      source  = "hashicorp/helm"
      version = "2.5.0"
    }
    kubectl = {
      source  = "gavinbunney/kubectl"
      version = ">= 1.7.0"
    }
  }

module "kube-prometheus-stack" {
  source = "github.com/ManagedKube/kubernetes-ops//terraform-modules/aws/helm/kube-prometheus-stack?ref=v2.0.82"

error:
 Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
│ 
│   with module.kube-prometheus-stack.helm_release.helm_chart,
│   on .terraform/modules/kube-prometheus-stack/terraform-modules/aws/helm/kube-prometheus-stack/main.tf line 1, in resource "helm_release" "helm_chart":
│    1: resource "helm_release" "helm_chart" {
│ 
╵
Operation failed: failed running terraform apply (exit 1)

**Comment by sekka1** [comment]
This MR parameterizes the version inputs: https://github.com/ManagedKube/kubernetes-ops/pull/446

It is set to the current version that it was hardcoded to so that it doesnt break current things that are using this.  You can use these new parameters to adjust which version you want to use.

**Comment by sekka1** [comment]
Released: https://github.com/ManagedKube/kubernetes-ops/releases/tag/v2.0.84

**Comment by sekka1** [comment]
This has been completed and should unblock you.  You will have to use this variable and select which version you want to use.
